name: Build Design Tokens

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'tokens/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'tokens/**'
  workflow_dispatch:

jobs:
  build-tokens:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build design tokens
      run: npm run build-tokens
    
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git diff --staged --quiet || git commit -m "Auto-generate design tokens [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
